app/urls.py
from django.urls import path, include

from .views import *


urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),

    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),

    path('account/', account, name='account'),
    path('account/saved/', account_saved_programs, name='saved_programs'),
    path('api/save_program/', api_save_program, name='api_save_program'),


    path('programs/', programs_list, name='program_list'),
    path('programs/<int:id>/', program_details, name='program_details'),

    path('universities/', university_list, name='university_list'),
    path('universities/<int:id>/', university_details, name='university_details'),

]

eduscraper/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('scraper/', include(('scraper.urls', 'scraper'), namespace='scraper')),
    path('', include(('app.urls', 'app'), namespace='app')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
{% extends "base.html" %} {% block content %}
<div class="w-full max-w-7xl mx-auto mt-12">
    {% load static %}
    <section
        class="card bg-primary-90 py-32 px-8 bg-[url('{% static 'images/bg/b.webp' %}')] bg-cover bg-top bg-no-repeat"
    >
        <h1 class="text-6xl font-bold">About Eduscraper</h1>
    </section>
    <section class="my-4 mx-auto">
        <article class="mx-auto text-justify prose lg:prose-lg xl:prose-xl">
            <p>
                Welcome to Edu Scraper, your ultimate source for educational
                data from universities worldwide. We are passionate about
                collecting and curating valuable information to empower
                students, researchers, and educators.
            </p>
            <p>
                Our mission is to provide a comprehensive database of
                university-related data, including courses, faculty information,
                admissions, and more. We strive to make this data easily
                accessible and user-friendly through our website.
            </p>
            <p>
                With Edu Scraper, you can explore universities, compare
                programs, and gain insights into the educational landscape.
                Whether you're seeking to find the perfect institution for your
                studies or conducting research in the field of education, our
                platform offers a wealth of data to support your journey.
            </p>
            <p>
                We are dedicated to maintaining data accuracy and regularly
                updating our database to ensure that you have access to the most
                current and reliable information. Our team works tirelessly to
                gather data from various sources, including university websites,
                official publications, and other reputable educational
                resources.
            </p>
            <p>
                Join us in harnessing the power of data to unlock new
                educational opportunities and make informed decisions. Explore
                our website, discover the vast world of academia, and embark on
                your educational adventure with Edu Scraper.
            </p>
        </article>
    </section>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-full">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Eduscraper</title>
        <script src="https://cdn.tailwindcss.com?plugins=aspect-ratio,forms,typography,line-clamp"></script>

        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.css"
            integrity="sha512-Z0kTB03S7BU+JFU0nw9mjSBcRnZm2Bvm0tzOX9/OuOuz01XQfOpa0w/N9u6Jf2f1OAdegdIPWZ9nIZZ+keEvBw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
            rel="stylesheet"
        />
        <script>
            tailwind.config = {
                theme: {
                    extend: {
                        fontFamily: {
                            inter: ["Inter", "sans-serif"],
                        },
                        colors: ({ colors }) => ({
                            primary: {
                                10: "#21005D",
                                20: "#381E72",
                                30: "#4F378A",
                                40: "#6750A4",
                                50: "#7F67BE",
                                60: "#9A82DB",
                                70: "#B69DF8",
                                80: "#D0BCFF",
                                90: "#EADDFF",
                            },
                            secondary: {
                                10: "#31111D",
                                20: "#332D41",
                                30: "#4A4458",
                                40: "#625B71",
                                50: "#7A7289",
                                60: "#958DA5",
                                70: "#B0A7C0",
                                80: "#CCC2DC",
                                90: "#E8DEF8",
                            },
                        }),
                    },
                },
            };
        </script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    </head>
    <body class="h-full font-inter flex flex-col min-h-screen">
        {% include 'header.html' %}
        <!---->
        {% block content %}{% endblock %}
        <!---->
        {% include 'footer.html' %}
        <script>
            function save_program(program_id) {
                url = "/api/save_program/?program=" + program_id;
                fetch(url)
                    .then((response) => response.json())
                    .then((data) => {
                        window.alert(data.message);
                        saveButton = document.getElementById(
                            "save-button-" + program_id
                        );
                        if (data.saved) {
                            saveButton.classList.remove("fa-regular");
                            saveButton.classList.add("fa-solid");
                        } else {
                            saveButton.classList.remove("fa-solid");
                            saveButton.classList.add("fa-regular");
                        }
                    })
                    .catch((error) => {
                        window.alert(data.message);
                    });
            }
        </script>
    </body>
</html>

templates/footer.html
<div
    class="mt-auto bottom-0 my-4 w-full max-w-7xl mx-auto flex items-center justify-between bg-primary-90 rounded-[40px]"
>
    <div>
        <a
            href="{% url 'app:index' %}"
            class="block my-4 mx-12 font-bold text-3xl text-primary-10"
            >EDUSCRAPER</a
        >
    </div>
    <div>
        <p class="mx-12">Copyright © 2023 Eduscraper</p>
    </div>
</div>

templates/header.html
<header
    class="sticky top-4 w-full max-w-7xl mx-auto mb-4 flex items-center justify-between bg-primary-90 rounded-[40px] shadow-lg"
>
    <div>
        <a
            href="{% url 'app:index' %}"
            class="block my-4 mx-12 font-bold text-3xl text-primary-10"
            >EDUSCRAPER</a
        >
    </div>
    <div>
        <ul class="flex justify-between gap-4">
            <li>
                <a
                    href="{% url 'app:program_list' %}"
                    class="block btn btn-nav py-6 px-16 h-full w-full"
                    >Programs</a
                >
            </li>
            <li>
                <a
                    href="{% url 'app:university_list' %}"
                    class="block btn btn-nav py-6 px-16 h-full w-full"
                    >Universities</a
                >
            </li>
            <li>
                <a
                    href="{% url 'app:about' %}"
                    class="block btn btn-nav py-6 px-16 h-full w-full"
                    >About</a
                >
            </li>
        </ul>
    </div>
    <div class="">
        {% if user.is_authenticated %}
        <a
            href="{% url 'app:account' %}"
            class="block btn btn-nav py-6 px-12 h-full w-full"
            >My Account</a
        >
        {% else %}
        <a
            href="{% url 'app:login' %}"
            class="block btn btn-nav py-6 px-12 h-full w-full"
            >Login</a
        >
        {% endif %}
    </div>
</header>

templates/index.html
{% extends "base.html" %} {% block content %}
<div class="w-full max-w-7xl mx-auto mt-8">
    {% load static %}
    <section
        class="py-48 px-8 card bg-primary-90 bg-[url('{% static 'images/bg/a.webp' %}')] bg-cover bg-center bg-no-repeat"
    >
        <h1 class="text-4xl lg:text-6xl font-bold text-slate-700">
            Discover Data from<br />
            Universities Worldwide
        </h1>
    </section>
    <section class="mt-16">
        <h1 class="text-center text-4xl font-bold text-slate-600">
            Top Viewed Programs
        </h1>
        <div class="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for program in programs %}
            <!---->
            {% include 'components/program_card.html' %}
            <!---->
            {% endfor %}
        </div>
    </section>
    <section class="mt-16">
        <h1 class="mt-12 text-center text-4xl font-bold text-slate-600">
            Top Universities
        </h1>
    </section>
    <section class="my-8">
        {% if universities|length == 0 %}
        <p class="text-center text-lg font-bold">
            No universities found for your search. Please try again with
            different keywords
        </p>
        {% endif %}
        <div class="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for university in universities %}
            <!---->
            {% include 'components/university_card.html' %}
            <!---->
            {% endfor %}
        </div>
    </section>
</div>

{% endblock %}

templates/program_details.html
{% extends "base.html" %} {% block content %}
<div class="w-full max-w-7xl mx-auto mt-12">
    {% load custom_filters %}
    <section class="relative card bg-primary-90 py-32 px-8">
        <h1 class="mt-4 text-6xl font-bold">{{program.title}}</h1>
         <a
                href="{{program.url}}"
                target="_blank"
                class="inline-block mt-4 btn btn-primary px-6 py-4"
                >Go To Program Wesbite</a
            >
             <button
                class="absolute bottom-8 right-8"
                onclick="save_program({{program.id}})"
            >
                <i
                    id="save-button-{{program.id}}"
                    class="text-3xl {% if program|is_saved:user %}fa-solid{% else %}fa-regular{% endif %} fa-heart"
                ></i>
            </button>
    </section>
    <div class="mt-4 grid lg:grid-cols-3 gap-4">
        <section class="col-span-2 grid gap-4">
            {% if program.details %}
            <div class="card bg-primary-90 p-8">
                <article class="prose lg:prose-lg">
                    <h2 class="text-3xl font-bold">Description</h1>
                    {{program.details | safe}}
                </article>
            </div>
            {% endif %}
            {% if program.requirements %}
            <div class="card bg-primary-90 p-8">
                <article class="prose lg:prose-lg">
                    <h2 class="text-3xl font-bold">Requirements</h1>
                    {{program.requirements | safe}}
                </article>
            </div>
            {% endif %}
            {% if program.apply_instructions %}
            <div class="card bg-primary-90 p-8">
                <article class="prose lg:prose-lg">
                    <h2 class="text-3xl font-bold">Apply Instructions</h1>
                    {{program.apply_instructions | safe}}
                </article>
            </div>
            {% endif %}
        </section>
        <section class="flex flex-col gap-4">
            {% include 'components/university_card.html' %}
            {% if program.duration %}
            <div class="card bg-primary-90 p-8">
                <article class="prose lg:prose-lg">
                    <h2 class="text-3xl font-bold">Program Duration</h1>
                    {{program.duration | safe}}
                </article>
            </div>
            {% endif %}
            <div class="card bg-primary-90 p-8">
                <article class=" prose lg:prose-lg">
                    <h2 class="text-3xl font-bold">Degrees Offered</h1>
                    {{program.degree | safe}}
                </article>
            </div>
            {% if program.contact %}
            <div class="card bg-primary-90 p-8">
                <article class="prose lg:prose-lg">
                    <h2 class="text-3xl font-bold">Contact</h1>
                    {{program.contact | safe}}
                </article>
            </div>
            {% endif %}
            {% if program.apply_link %}
            <div class="card bg-primary-90 p-8">
                <article class="prose lg:prose-lg">
                    <h2 class="text-3xl font-bold">Contact</h1>
                    {{program.apply_link | safe}}
                </article>
            </div>
            {% endif %}
            

        </section>
    </div>
</div>

{% endblock %}

templates/programs.html
{% extends "base.html" %} {% block content %}
<div class="w-full max-w-7xl mx-auto mt-8 mb-4">
    {% load static %}
    <form action="">
        <section
            class="card bg-primary-90 py-32 px-8 bg-[url('{% static 'images/bg/c.webp' %}')] bg-cover bg-top bg-no-repeat"
        >
            <h1 class="text-6xl font-bold">Explore Programs</h1>
            <p class="mt-4 font-bold">
                List of programs we have in our database. Sort and search
                according to your needs
            </p>
        </section>
        {% include 'components/search.html' %}
        <section class="mt-8">
            {% if programs|length == 0 %}
            <p class="text-center text-lg font-bold">
                No programs found for your search. Please try again with
                different keywords
            </p>
            {% endif %}
            <div
                class="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4"
            >
                {% for program in programs %}
                <!---->
                {% include 'components/program_card.html' %}
                <!---->
                {% endfor %}
            </div>
        </section>
    </form>
</div>

{% endblock %}

templates/universities.html
{% extends "base.html" %} {% block content %}
<div class="w-full max-w-7xl mx-auto mt-12">
    {% load static %}
    <section
        class="card bg-primary-90 py-32 px-8 bg-[url('{% static 'images/bg/c.webp' %}')] bg-cover bg-top bg-no-repeat"
    >
        <h1 class="mt-4 text-6xl font-bold">List of Universities</h1>
    </section>
    <section class="mt-8">
        {% if universities|length == 0 %}
        <p class="text-center text-lg font-bold">
            No universities found for your search. Please try again with
            different keywords
        </p>
        {% endif %}
        <div class="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for university in universities %}
            <!---->
            {% include 'components/university_card.html' %}
            <!---->
            {% endfor %}
        </div>
    </section>
</div>

{% endblock %}

templates/university_details.html
{% extends "base.html" %} {% block content %} {% load static %}
<div class="w-full max-w-7xl mx-auto mt-16">
    <form action="">
        <section class="card bg-primary-90 py-32 px-8">
            <img
                src="/media/{{university.logo}}"
                alt=""
                class="h-24 {% if university.id == 2 %}invert{% endif %}"
            />
            <h1 class="mt-4 text-6xl font-bold">{{university}}</h1>
            <a
                href="{{university.url}}"
                target="_blank"
                class="inline-block mt-4 btn btn-primary px-6 py-4"
                >Go To Wesbite</a
            >
        </section>
        <section class="mt-16">
            <h1 class="text-3xl font-bold text-center">
                Programs Offered by {{university}}
            </h1>
        </section>
        {% include 'components/search.html' %}
        <section class="mt-8">
            {% if university.programs.all|length == 0 %}
            <p class="text-center text-lg font-bold">
                No programs found for this university.
            </p>
            {% endif %}
            <div
                class="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4"
            >
                {% for program in university.programs.all %}
                <!---->
                {% include 'components/program_card.html' %}
                <!---->
                {% endfor %}
            </div>
        </section>
    </form>
</div>

{% endblock %}