app/urls.py
from django.urls import path, include

from .views import *


urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),

    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),

    path('account/', account, name='account'),
    path('account/saved/', account_saved_programs, name='saved_programs'),
    path('api/save_program/', api_save_program, name='api_save_program'),


    path('programs/', programs_list, name='program_list'),
    path('programs/<int:id>/', program_details, name='program_details'),

    path('universities/', university_list, name='university_list'),
    path('universities/<int:id>/', university_details, name='university_details'),

]

eduscraper/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('scraper/', include(('scraper.urls', 'scraper'), namespace='scraper')),
    path('', include(('app.urls', 'app'), namespace='app')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/components/program_card.html
{% load static %} {% load custom_filters %}

<div
    class="card bg-primary-90 hover:bg-primary-80 transition duration-300 ease-in-out"
>
    <div
        id="program-card-image-{{program.id}}"
        class="card h-48 flex justify-center items-center bg-secondary-80/50 bg-blend-overlay bg-cover bg-center"
    >
        <p class="text-slate-600 text-4xl text-center mt-2 font-bold">
            {{program.title}}
        </p>
    </div>
    <div class="p-4 relative">
        <button
            class="absolute right-4 top-4"
            onclick="save_program({{program.id}})"
        >
            <i
                id="save-button-{{program.id}}"
                class="text-2xl {% if user.is_authenticated %}{% if program|is_saved:user %}fa-solid{% else %}fa-regular{% endif %}{% else %}fa-regular{% endif %} fa-heart"
            ></i>
        </button>
        <a
            href="{% url 'app:program_details' program.id %}"
            class="hover:underline"
        >
            <h2 class="text-lg font-bold mr-4">{{program.title}}</h2>
        </a>
        <a
            href="{% url 'app:university_details' program.university.id %}"
            class="mt-4 flex items-center gap-4 hover:underline"
        >
            <img
                src="/media/{{program.university.logo}}"
                alt=""
                class="h-8 {% if program.university.id == 2 %}invert{% endif %}"
            />{{program.university}}
        </a>
    </div>
</div>
<script>
    function setRandomBackground() {
        var divElement = document.getElementById(
            "program-card-image-{{program.id}}"
        );
        var images = ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"];
        var randomIndex = Math.floor(Math.random() * images.length);
        var randomImage = images[randomIndex];
        var imageUrl = "{% static 'images/bg/' %}" + randomImage;
        divElement.style.backgroundImage = "url(" + imageUrl + ")";
    }

    setRandomBackground();
</script>

templates/components/search.html
<section class="mt-8 card rounded-[40rem] flex justify-between">
    <div
        class="relative rounded-[40rem] bg-primary-90 flex items-center text-sm"
    >
        <input
            type="text"
            class="border-none bg-transparent rounded-[40rem] w-full h-full p-4 focus:outline-none focus:ring focus:ring-violet-300"
            placeholder="Search"
            id="search"
            name="q"
            value="{{request.GET.q}}"
        />
        <button
            class="absolute right-0 btn btn-primary h-12 w-12 flex flex-col justify-center items-center rounded-full"
        >
            <i class="fa-solid fa-search"></i>
        </button>
    </div>
    {% if not hide_university %}
    <div
        class="relative rounded-[40rem] bg-primary-90 flex items-center text-sm"
    >
        <select
            class="border-none bg-transparent rounded-[40rem] w-full h-full py-4 px-8 focus:outline-none focus:ring focus:ring-violet-300 font-bold"
            id="university"
            name="university"
            onchange="this.form.submit()"
        >
            <option value="">Select University to Filter</option>
            <option value="">All</option>
            {% for university in universities %}
            <option value="{{university.id}}" {% if request.GET.university == university.id|stringformat:'i' %}selected {% endif %}>{{university}}</option>
            {% endfor %}
        </select>
    </div>
    {% endif %}
    {% if not hide_degree %}
    <div
        class="relative rounded-[40rem] bg-primary-90 flex items-center text-sm"
    >
        <select
            class="border-none bg-transparent rounded-[40rem] w-full h-full py-4 px-8 focus:outline-none focus:ring focus:ring-violet-300 font-bold"
            name="degree"
            id="degree"
            onchange="this.form.submit()"
        >
            <option value="">Select Degree to Filter</option>
            <option value="">All</option>
            <option value="bsc" {% if request.GET.degree == 'bsc' %}selected {% endif %}>BSc.</option>
            <option value="msc" {% if request.GET.degree == 'msc' %}selected {% endif %}>MSc.</option>
            <option value="ma" {% if request.GET.degree == 'ma' %}selected {% endif %}>MA</option>
            <option value="mba" {% if request.GET.degree == 'mba' %}selected {% endif %}>MBA</option>
            <option value="mcom" {% if request.GET.degree == 'mcom' %}selected {% endif %}>MCOM</option>
            <option value="phd" {% if request.GET.degree == 'phd' %}selected {% endif %}>PhD.</option>
        </select>
    </div>
    {% endif %}
    <div
        class="text-sm"
    >
            <button
                class=" btn btn-primary h-full px-16"
                onclick="resetForm(); this.form.submit();"
            >
                Reset
            </button>
    </div>
</section>

<script>
    function resetForm() {
        document.getElementById("search").value = "";
        {% if not hide_university %}
        document.getElementById("university").value = "";
        {% endif %}
        {% if not hide_degree %}
        document.getElementById("degree").value = "";
        {% endif %}
    }
</script>

templates/components/university_card.html
{% load static %}
<div
    class="card bg-primary-90 hover:bg-primary-80 transition duration-300 ease-in-out"
>
    <a href="{% url 'app:university_details' university.id %}">
        <div
            class="card h-48 flex justify-center items-center bg-white bg-blend-overlay bg-cover bg-center"
        >
            <img
                src="/media/{{university.logo}}"
                alt=""
                class="h-1/2 {% if university.id == 2 %}invert{% endif %}"
            />
        </div>
        <div class="p-4">
            <h2 class="text-lg font-bold">{{university}}</h2>
        </div>
    </a>
</div>
<script></script>